import Container from "@/layout/Container/Container";
import "./globals.css";
import Center from "@/layout/Center/Center";

export const metadata = {
    title: "gen_sheep",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Container>
                    <Center>
                        {children}
                    </Center>
                </Container>
            </body>
        </html>
    );
}
